export default {
  "login": "amelakor",
  "id": 31077388,
  "node_id": "MDQ6VXNlcjMxMDc3Mzg4",
  "avatar_url": "https://avatars1.githubusercontent.com/u/31077388?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/amelakor",
  "html_url": "https://github.com/amelakor",
  "followers_url": "https://api.github.com/users/amelakor/followers",
  "following_url": "https://api.github.com/users/amelakor/following{/other_user}",
  "gists_url": "https://api.github.com/users/amelakor/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/amelakor/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/amelakor/subscriptions",
  "organizations_url": "https://api.github.com/users/amelakor/orgs",
  "repos_url": "https://api.github.com/users/amelakor/repos",
  "events_url": "https://api.github.com/users/amelakor/events{/privacy}",
  "received_events_url": "https://api.github.com/users/amelakor/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": "Agent Locator",
  "blog": "",
  "location": "Sarajevo",
  "email": null,
  "hireable": null,
  "bio": "Web Developer",
  "twitter_username": null,
  "public_repos": 5,
  "public_gists": 0,
  "followers": 0,
  "following": 1,
  "created_at": "2017-08-16T18:20:27Z",
  "updated_at": "2020-09-11T06:38:23Z"
};